CREATE TABLE IF NOT EXISTS `api_exchange` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `request_id` VARCHAR(128) NOT NULL,
  `execution_id` VARCHAR(128) NOT NULL,
  `case_id` VARCHAR(64) NOT NULL,
  `trace_id` VARCHAR(255) NOT NULL,
  `segment_id` VARCHAR(255) DEFAULT NULL,
  `method` VARCHAR(16) NOT NULL,
  `url` VARCHAR(2048) NOT NULL,
  `resource_type` VARCHAR(32) DEFAULT NULL,
  `status_code` INT DEFAULT NULL,
  `duration_ms` BIGINT DEFAULT NULL,
  `content_type` VARCHAR(255) DEFAULT NULL,
  `request_headers` MEDIUMTEXT DEFAULT NULL,
  `request_body_base64` MEDIUMTEXT DEFAULT NULL,
  `request_body_truncated` TINYINT(1) NOT NULL DEFAULT 0,
  `response_headers` MEDIUMTEXT DEFAULT NULL,
  `response_body_base64` MEDIUMTEXT DEFAULT NULL,
  `response_body_truncated` TINYINT(1) NOT NULL DEFAULT 0,
  `error_message` VARCHAR(1024) DEFAULT NULL,
  `started_at` DATETIME(3) DEFAULT NULL,
  `completed_at` DATETIME(3) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_api_exchange_execution_request` (`execution_id`, `request_id`),
  KEY `idx_api_exchange_execution` (`execution_id`), KEY `idx_api_exchange_trace` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
